version: "3.7"
services:
  app:
    build:
      args:
        user: frAuthUser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: gcr.io/fr-auth
    container_name: fr-auth
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - fr-auth

  db:
    image: mysql:8.0
    container_name: fr-auth-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - fr-auth

  nginx:
    image: nginx:alpine
    container_name: fr-auth-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - fr-auth

networks:
  fr-auth:
    driver: bridge



